name: local_scheduled_notification
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.2
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^7.6.7
  injectable: ^2.3.2

  # Freezed for Immutable Models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Utils
  intl: ^0.19.0
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  # Code Generation
  build_runner: ^2.4.8
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true
